---
- name: Creates /root/.ssh
  file:
    path: /root/.ssh
    state: directory
    mode: 0700
    owner: root
    group: root
    
- name: Update /root/.authorized_keys
  template:
    src: "root/authorized_keys.j2"
    dest: "/root/.ssh/authorized_keys"
    owner: root
    group: root
    mode: 0644
    
# tasks file for home
