---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

  tasks:
    - name: "Include home"
      include_role:
        name: "home"
